config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  	resources :questions do
  		resources :answers, only:[:create] do
  			resources :comeanswers
  		end
  		resources :comequestions  		
  		resources :voteanswers, only: [:create, :destroy]
  		resources :votequestions, only: [:create, :destroy]
  	end
  	root 'questions#index'
end

app/models/answer.rb
class Answer < ApplicationRecord
	validates :descripcion, presence: { message: "Respuesta vacía!"}
	validates :descripcion, :presence => {:message => "Usted debe ingresar una descripción"}
	belongs_to :user
	belongs_to :question
	has_many :comeanswers
	has_many :voteanswers

	def avotada?(user)
			voteanswers.exists?(user: user)			
	end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/comeanswer.rb
class Comeanswer < ApplicationRecord
	validates :descripcion, presence: true
	belongs_to :user
	belongs_to :answer
end

app/models/comequestion.rb
class Comequestion < ApplicationRecord
	validates :descripcion, presence: true
	belongs_to :user
	belongs_to :question
end

app/models/question.rb
class Question < ApplicationRecord
	validates :titulo, presence: true
	validates :descripcion, presence: true
	belongs_to :user
	has_many :answers
	has_many :comequestions
	has_many :votequestions

	def self.search(search)
		where("titulo ILIKE ? OR descripcion ILIKE ?","%#{search}%","%#{search}%")
	end

	def qvotada?(user)
			votequestions.exists?(user: user)			
	end
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  validates :encrypted_password, presence: true
  validates :email, uniqueness: {case_sensitive: false ,message: "Ese mail ya fue registrado"}
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
   validates :email, format: { :with => VALID_EMAIL_REGEX , message: "El formato del correo es invalido" }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  has_many :questions
  has_many :answers
  has_many :votequestions
  has_many :voteanswers
end

app/models/voteanswer.rb
class Voteanswer < ApplicationRecord
  belongs_to :answer
  belongs_to :user
end

app/models/votequestion.rb
class Votequestion < ApplicationRecord
  belongs_to :question
  belongs_to :user
end

app/controllers/answers_controller.rb
class AnswersController < ApplicationController
	def create

		question = Question.find(params[:question_id])
  		h=question.answers.create(answer_params)

  		if h.save
  			redirect_to question
  		else
  			redirect_to question, alert: "ERROR: Respuesta vacía!"
		end
	end
	protected
	def answer_params
      params.require(:answer).permit(:descripcion).merge(user: current_user)
	end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  
end

app/controllers/comequestions_controller.rb
class ComequestionsController < ApplicationController
		
	def create
		question = Question.find(params[:question_id])
  		h=question.comequestions.create(comequestion_params)
  		if h.save
  			redirect_to question
  		else
  			redirect_to question, alert: "ERROR: Comentario vacío!"
		end
  		
	end
	
	
	protected
	def comequestion_params
      params.require(:comequestion).permit(:descripcion).merge(user: current_user)
	end
end

app/controllers/concerns/comeanswers_controller.rb
class ComeanswersController < ApplicationController
		
	def create
		answer = Answer.find(params[:answer_id])
  		h=answer.comeanswers.create(comeanswer_params)
  		if h.save
  			redirect_to :back
  		else
  			redirect_to :back, alert: "ERROR: Comentario vacío!"
		end
  		
  		
	end
	
	
	protected
	def comeanswer_params
      params.require(:comeanswer).permit(:descripcion).merge(user: current_user)
	end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	before_action :authenticate_user!, except: [:index, :show]
	def index
		@question=Question.order(created_at: :desc)
		if params[:search]
			@question=Question.search(params[:search]).order(created_at: :desc)
		else
			@question=Question.order(created_at: :desc)
		end
	end
	def new
		@question = current_user.questions.build
	end
	def show
		@question = Question.find(params[:id])
	end
	def create
		@question = current_user.questions.build(question_params)
		if @question.save
			redirect_to questions_path, notice: "La pregunta se ingreso correctamente"
		else
			render :new
		end
	end
	protected
	def question_params
      params.require(:question).permit(:titulo, :descripcion)
end
end

app/controllers/voteanswers_controller.rb
class VoteanswersController < ApplicationController
	def create
	  answer = Answer.find(params[:question_id])
	  answer.voteanswers.create(user: current_user)

	  redirect_to :back
	end

	def destroy
	  answer = Answer.find(params[:question_id])
	  answer.voteanswers.where(user: current_user).take.try(:destroy)

	   redirect_to :back
	end
	
end

app/controllers/votequestions_controller.rb
class VotequestionsController < ApplicationController
	def create
	  question = Question.find(params[:question_id])
	  question.votequestions.create(user: current_user)

	  redirect_to question_path(params[:question_id])
	end

	def destroy
	  question = Question.find(params[:question_id])
	  question.votequestions.where(user: current_user).take.try(:destroy)

	  redirect_to question_path(params[:question_id])
	end
	
end

app/helpers/answers_helper.rb
module AnswersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
	def markdown(content)
		renderer = Redcarpet::Render::HTML.new(hard_wrap: true, filter_html: true)
		options = {
			autolink: true,
			no_intra_emphasis: true,
			disable_indented_code_blocks: true,
			fenced_code_blocks: true,
			lax_html_blocks: true,
			strikethrough: true,
			superscript: true
		}
		Redcarpet::Markdown.new(renderer,options).render(content).html_safe
	end
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Qoverflow</title>
    <%= csrf_meta_tags %>
    <link rel="icon" type="image/ico" href="/assets/qoverflow.ico">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/questions/_form.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
  	<div class="navbar-form navbar-left">
  		<img class="logo" src="<%= image_url "qoverflow_logo.png" %>">
  	</div>
    <form class="navbar-form navbar-right" role="search">
    <% if user_signed_in? %>
      <a class="btn btn-default botones-a botones-b" role="button" href="<%= url_for(destroy_user_session_path)%>" data-method="delete"> Salir del Sistema</a>
    <% else %>
        <a class="btn btn-default botones-a botones-b" role="button" href="<%= new_user_session_path %>">Ingresar</a>
        <a class="btn btn-default botones-a botones-b" role="button" href="<%= new_user_registration_path %>">Registrarse</a>
    <% end %>
    	
      
    </form>
  </div>
</nav>
<div class="container">
	<div class="row">
	<p><a class="btn btn-primary btn-sm" href="/" role="button">Volver</a></p>
	</div>
	<div class="row">
		<div class="col-sm-6 col-sm-offset-3">
			<h1 class="centrado"><%= @question.new_record? ? "Publicar": "Editar" %> Pregunta</h1>

				<% if @question.errors.any? %>
				  <div class="alert alert-danger">
				    <ul>
				    <% @question.errors.full_messages.each do |msg| %>
				      <li><%= msg %></li>
				    <% end %>
				    </ul>
				  </div>
				<% end %>
				<%= form_for @question do |p| %>
				       <div class="form-group">
				         <%= p.text_field :titulo, class: 'form-control input-lg', placeholder: "Escribe el título de la pregunta" %>
				       </div>
				
				       <div class="form-group">
				         <%= p.text_area :descripcion, class: 'form-control input-lg', placeholder: "Expresa claramente tu pregunta ...", rows: "10" ,"data-provide" => "markdown" %>
				       </div>
				       <div class="actions text-right">
				                 <%= p.submit @question.new_record? ? "Nueva Pregunta" : "Editar Pregunta", class: "btn btn-primary btn-lg btn-block" %>
				        </div>
				        <div class="blankspace"></div>
				<% end %>
		</div>  		
	</div>
</div>
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="piecito">
    <p>____________________________________________</p>
  <p><a href="http://www.monkodev.com" target="_blank"><img class="logofondo" src="<%= image_url "monkodevlogo.png" %>"> Powered by Monkodev.com</a></p>
  </div>
</nav>

app/views/questions/index.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
  	<div class="navbar-form navbar-left">
  		<img class="logo" src="<%= image_url "qoverflow_logo.png" %>">
  	</div>
    <form class="navbar-form navbar-right" role="search">
    <% if user_signed_in? %>
      <a class="btn btn-default botones-a botones-b" role="button" href="<%= url_for(destroy_user_session_path)%>" data-method="delete"> Salir del Sistema</a>
    <% else %>
        <a class="btn btn-default botones-a botones-b" role="button" href="<%= new_user_session_path %>">Ingresar</a>
        <a class="btn btn-default botones-a botones-b" role="button" href="<%= new_user_registration_path %>">Registrarse</a>
    <% end %>
    	
      <div class="form-group botones-a">
        <%= form_tag(questions_path, :method => "get", id: "search-form") do %>
        <%= text_field_tag :search, params[:search], placeholder: "Buscar" %>
        <%= submit_tag "Search", name:nil, :style => "display: none;" %>
        <% end %>
        
      </div>     
    </form>
  </div>
</nav>
<% flash.each do |name, msg| -%>
<div class="alert alert-success">
      <%= content_tag :div, msg, class: name %>
</div>
<% end -%>
<div class="container">
  <div class="row">
      <img class="logo1" src="<%= image_url "preguntas.png" %>">
      
       <div class="pull-right" style="margin-right: 60px;">
       <p><a class="btn btn-primary" href="/questions/new" role="button">Ingresar una pregunta</a></p>
       </div> 
  </div> 

 <table class="table">
  <% @question.each do |q| %>
  
    <tr>
      <td><h4 class="orange"> <%= q.votequestions.count %></h4>
      <p><h4 class="centrado"><small>Votos</small></h4></p>
      </td>
      <td><h4 class="orange"><%= q.answers.count %></h4> 
      <p><h4 class="centrado"><small>
      Respuestas</small></h4></p>
      </td>
      <td><h4> <%= link_to q.titulo, q %> </h4>
        <p>
          <h4><small>Preguntó <%= q.user.email %> hace <% dife = (Time.now - q.created_at).to_i %>
          <% if (dife > 31536000) %>
            <%= (dife/31536000).to_i %> años
          <% else %>
            <% if (dife > 2592000) %>
              <%= (dife/2592000).to_i %> meses
              <% else %>
                <% if (dife > 86400) %>
                  <%= (dife/86400).to_i %> días
                  <% else %>
                  <% if (dife > 3600) %>
                    <%= (dife/3600).to_i %> horas
                  <% else %>
                    <% if (dife > 60) %>
                    <%= (dife/60).to_i %> minutos
                    <% else %>
                    <%= dife %> segundos
                    <% end %>
                  <% end %>
                <% end %>
              <% end %>
          <% end %>
          
          </small></h4>
        </p>
      </td>
    </tr>
  
<% end %>
</table>
      
          
     
  
</div>
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="piecito">
    <p>____________________________________________</p>
  <p><a href="http://www.monkodev.com" target="_blank"><img class="logofondo" src="<%= image_url "monkodevlogo.png" %>"> Powered by Monkodev.com</a></p>
  </div>
</nav>

app/views/questions/new.html.erb
<%= render 'form' %>

app/views/questions/show.html.erb
<nav class="navbar navbar-default navbar-static-top">
  <div class="container">
  	<div class="navbar-form navbar-left">
  		<img class="logo" src="<%= image_url "qoverflow_logo.png" %>">
  	</div>
    <form class="navbar-form navbar-right" role="search">
    <% if user_signed_in? %>
      <a class="btn btn-default botones-a botones-b" role="button" href="<%= url_for(destroy_user_session_path)%>" data-method="delete"> Salir del Sistema</a>
    <% else %>
        <a class="btn btn-default botones-a botones-b" role="button" href="<%= new_user_session_path %>">Ingresar</a>
        <a class="btn btn-default botones-a botones-b" role="button" href="<%= new_user_registration_path %>">Registrarse</a>
    <% end %>
    	   
    </form>
  </div>
</nav>
<% flash.each do |name, msg| -%>
<div class="alert alert-info">
      <%= content_tag :div, msg, class: name %>
</div>
<% end -%>
<div class="container">
  <div class="row">
  <p><a class="btn btn-primary btn-sm" href="/" role="button">Volver</a></p>
  </div>
  <div class="row">
    <div class="col-sm-10">
    <div class="panel panel-heading">
    <div class="panel-title">
      <h3 class="style_text_title"><img class="logo2" src="<%= image_url "brain.png" %>"><%= @question.titulo %></h3>
      </div>
      <div class="row">
        <div class="col-sm-1 pregunta5 centrado">

          <% if @question.qvotada? current_user %>
                      <%= link_to question_votequestion_path(@question), method: :delete, class: "product-upvote upvote-active" do %>
                        <span class="upvote-arrow"></span>
                        <span class="upvote-count"><%= @question.votequestions.count %></span>
                      <% end %>
                    <% else %>
                      <%= link_to question_votequestions_path(@question), method: :post, class: "product-upvote" do %>
                        <span class="upvote-arrow"></span>
                        <span class="upvote-count"><%= @question.votequestions.count %></span>
                      <% end %>
          <% end %>

        </div>
         <div class="col-sm-9">
            <p><%= markdown(@question.descripcion) %></p>

            <footer class="blockquote-footer"><small> Preguntó <%= @question.user.email %> el <%= @question.created_at.strftime("%d/%m/%Y a las %I:%M%p") %></small></footer>
          </div>
      </div>
      
     
      </div> 
      <div class="row">
        <div class="col-sm-1"></div>
        <div class="col-sm-11 pregunta">
           <% @question.comequestions.each do |cq| %>
        <div class="panel pregunta"><%= markdown(cq.descripcion) %> <small>comentó <%= cq.user.email %></small></div>    
      <% end %> 
      <% if signed_in? %>
        <%= form_for [@question, @question.comequestions.build] do |f| %>
          <div class="form-group pregunta">
            <%= f.text_area :descripcion, class: "form-control", placeholder: "Ingresa tu comentario ..." %>
          </div>
         
          <div class="actions text-right">
            <%= f.submit "Comentar", class: "btn btn-primary" %>
          </div>
        <% end %>
      <% end %>  
        </div>
      </div>
     
      <div class="blankspace2"></div>
      <div class="panel panel-default pregunta">
        <div class="panel-heading blankspace3">
        <div class="col-sm-4">
          <strong><%= @question.answers.count %> Respuesta(s)</strong>
        </div>
        <div class="col-sm-8 right_side">
            Contribuye con tu conocimiento  ...  <span class="label label-danger">Responde ya esta pregunta!</span>
        </div></div>
      </div>
      <div class="row">
          <% @question.answers.each do |ca| %>
            <div class="col-sm-1 pregunta">
              
              <% if ca.avotada? current_user %>
                      <%= link_to question_voteanswer_path(ca), method: :delete, class: "product-upvote upvote-active" do %>
                        <span class="upvote-arrow"></span>
                        <span class="upvote-count"><%= ca.voteanswers.count %></span>
                      <% end %>
                    <% else %>
                      <%= link_to question_voteanswers_path(ca), method: :post, class: "product-upvote" do %>
                        <span class="upvote-arrow"></span>
                        <span class="upvote-count"><%= ca.voteanswers.count %></span>
                      <% end %>
          <% end %>
            </div>
             <div class="col-sm-10 panel">
                  <div class="panel panel-default">
                    <div class="panel-body panelito">
                        <%= markdown(ca.descripcion) %> <small>respondió <%= ca.user.email %></small>
                    </div>
                  </div>
             </div>   
             <div class="col-sm-1"> </div>
              <div class="col-sm-10">
              
                       <% ca.comeanswers.each do |cca| %>
                    <div class="panel pregunta"><%= markdown(cca.descripcion) %> <small>comentó <%= cca.user.email %></small></div>    
                  <% end %>  


              </div>
              <div class="row espacia2">
              <div class="col-sm-1"> </div>
              <div class="col-sm-10 col-sm-offset-2 derecha">
              
                    <% if signed_in? %>
                        <%= form_for [@question,ca, ca.comeanswers.build] do |cab| %>
                        <div class="form-group pregunta">
                            <%= cab.text_area :descripcion, class: "form-control", placeholder: "Comentar esta respuesta" %></ br>
                        </div>

                        <div class="actions text-right">
                            <%= cab.submit "Comentar", class: "btn btn-primary" %>
                        </div>
                        <% end %>
                    <% end %> 
                  </div>

                </div>

            <% end %> 
              <div class="blankspace2"></div></ br>
            </div>
          
          <% if signed_in? %>
              <%= form_for [@question, @question.answers.build] do |f| %>
              <div class="form-group pregunta">
                  <%= f.text_area :descripcion, class: "form-control", placeholder: "Ingresa tu respuesta ..." %>
              </div>

              <div class="actions text-right">
                  <%= f.submit "Publicar respuesta", class: "btn btn-danger" %>
              </div>
              <% end %>
          <% end %>  
    
      <div class="blankspace"></div>
    </div>      
  </div>
</div>
<nav class="navbar navbar-default navbar-fixed-bottom">
  <div class="piecito">
    <p>____________________________________________</p>
  <p><a href="http://www.monkodev.com" target="_blank"><img class="logofondo" src="<%= image_url "monkodevlogo.png" %>"> Powered by Monkodev.com</a></p>
  </div>
</nav>